### ISSUE TITLE
Not working with  Blender 3.92

### ISSUE THREAD

**Issue by aboim2** [rebootl/simple_yasim_import-git#4]
This addon is not working with  Blender 3.92!
It says it was installed but after checking all around it seems it is not available!

**Comment by Biblo2228** [comment]
I made a small hack to use it with Blender 2.83. It is not a complete rework but a modified code that imported the most  of de data. Only modified code that I used as a script in Blender. Not tested in 3.92.

**Comment by rebootl** [comment]
Hello, I have not worked on this addon in a very long time.
@Biblo2228 could you create a pull request with your fix?

**Comment by rebootl** [comment]
Hello, thanks for reporting here.
I merged the changes from https://github.com/alexeijd/simple_yasim_import-git/tree/2.80
- [commit](https://github.com/rebootl/simple_yasim_import-git/commit/9bc2681a1376f817799e2c60ca6ef643223bb805)
This should fix the issue.
